[ESC-50] Esc 50 back nickname request
earth-saving-cleaner/earth-saving-cleaner-backend pull request #13
Opened 2022-02-08 18:47 UTC by JK-Yun777

# [[ESC-50]] {Esc 50 back nickname request}
[50] nickname logic
## jira 칸반 링크

- [Esc 50 back nickname request](https://earth-saving-cleaner.atlassian.net/browse/ESC-50)

## 카드에서 구현 혹은 해결하려는 내용
- 입력된 사용자 nickname 의 중복 가입 여부 확인 후 없다면 User 스키마에 신규 등록하고 토큰 발급한다.
- 중복 가입자의 경우 exsisting nickname  응답

## 테스트 방법
- App.js 에서 signup 컴포넌트 import 후 진행
-
## 기타 사항
signup page flow
중복 가입자일 경우 exsisting nickname  응답 보낼 때 구글 토큰을 함께 전송 
-> 사용자가 닉네임 기입하면 함께 보냈던 구글 토큰을 서버로 전송 
-> 닉네임 유효성 검증 되면 해당 구글 토큰에서 사용자 정보 확인 후 DB User 스키마에 신규 등록합니다.

2022-02-08 22:43 UTC, CoRoRo10 reviewed
진경님 코드 잘 구현해주셨네요👍 고생하셨습니다~!

2022-02-08 22:43 UTC, CoRoRo10 commented on middlewares/authJwt.js
> +  }
토큰이 만료되었을 때는 다른 메시지의 에러를 전달해주어야 할 것 같습니다~!
토큰이 만료되었거나 unauthorized한 상황 모두 처리를 해주면 좋을 것 같네요😃

2022-02-08 22:43 UTC, CoRoRo10 commented on routes/login.js
> +module.exports = router;
login과 signup이 다른 파일로 분리되지 않아도 될 것 같다는 생각이 들었습니다~!
하지만 end point에 따른 라우터 분리로 이렇게 구성하신 것 같은데 이건 회의를 통해서 end point를 수정할건지 파일을 나눠서 갈 것인지, 라우터 파일 분리없이 routes index에서 바로 contoller를 호출할 것인지 정하면 좋겠네요~!

2022-02-09 05:01 UTC, JK-Yun777 commented on contorollers/login.js
> +      });
제가 판단했을 때는 위에서 유효한 데이터인지 모두 검증된 상태이고,  말씀하신 로직은 토큰을 만들어내는 과정이므로 
오류가 발생하는 경우의 수는 서버쪽 문제일 것이라는 판단이었습니다.

2022-02-09 05:02 UTC, Kyeong1024 commented on services/signup.js
> +};
고생하셨습니다.👍

2022-02-09 05:08 UTC, JK-Yun777 commented on middlewares/authJwt.js
> +  }
좋은 의견입니다.  경우의 수 나눠서 분기 처리 진행하는 것으로 수정하겠습니다~ 😄

2022-02-09 05:10 UTC, JK-Yun777 commented on routes/login.js
> +module.exports = router;
이 부분은 프론트 작업하면서도 느끼기는 했는데, 언급하신데로 회의를 통해 결정하는게 저도 좋을 것 같습니다~

2022-02-09 05:13 UTC, JK-Yun777 commented on middlewares/authJwt.js
> +    const myToken = await jwt.verify(token);
mytoken이 유효하지 않다면, 밑에 if문으로 내려가지 않고, 바로 catch 문으로 전달되기 때문에 위와 같이 작성했습니다~

2022-02-09 08:09 UTC, CoRoRo10 requested changes

2022-02-09 08:09 UTC, CoRoRo10 commented on middlewares/authJwt.js
> +  }
로직 정리가 조금 필요할 것 같습니다...! 제가 이해한 바로는 try-catch로 감싸고 try 안에서는 다시 if-else로 unauthorizedResult를 거르고 catch 에서는 같은 에러 코드를 메시지만 다르게 보내는 상황인 것 같습니다~! 아 그리고 제가 test할 때는 err.name === "TokenExpiredError"이면 만료된 토큰으로 나왔는데 message는 확인을 못해서 혹시 진경님께서 message를 확인하셨는지 한 번 여쭤봅니다🙇‍♀️

```suggestion
  try {
    //  try 구문으로 감싸져 있기 때문에 verify 되지 않는다면 바로 catch로 넘어갈 것 같습니다.
    const clientToken = await jwt.verify(token);
    req.id = clientToken.id;
    req.email = clientToken.email;
  
    next();
  } catch (err) {
    console.error(err);
    const message =
      err.name === "TokenExpiredError"
        ? resultMsg.tokenExpired
        : resultMsg.unauthorized;

    next(createError(401, message));
}
```

2022-02-09 08:09 UTC, CoRoRo10 commented on middlewares/authJwt.js
> +        message: "토큰 유효기간이 만료되었습니다. 로그인이 필요합니다",
이 메시지도 resultMsg를 이용하면 더욱 일관성 있는 코드가 되지 않을까요~?

2022-02-09 09:59 UTC, JK-Yun777 commented on middlewares/authJwt.js
> +  }
넵 위에서 제안된 코드에 명시 하셨듯 name = "TokenExpiredError" 이고, 
message = "jwt expired" 입니다 (확인 완료 한건)

제안해주신 코드로 수정해서 커밋 올리겠습니다!

2022-02-09 10:01 UTC, JK-Yun777 commented on middlewares/authJwt.js
> +        message: "토큰 유효기간이 만료되었습니다. 로그인이 필요합니다",
딱 한군데만 쓰이는 문구에 resultMsg 에 한글들어가면 더 이상할 것 같아서 위와 같이 쓰긴 했는데,
민지님께서 제안해주신 코드로 수정 진행해서 더이상 쓰이지 않는 코드가 될 것 같습니다 ㅎㅎ

2022-02-09 12:27 UTC, CoRoRo10 commented on middlewares/authJwt.js
> +        message: "토큰 유효기간이 만료되었습니다. 로그인이 필요합니다",
client로 결과를 보낼 때 어떤 message는 한글, 어떤 message는 영문이면 client로직에서 처리하는데 혼란이 올 수 있을 것 같다는 생각이 들어서 코멘트 드렸습니다😃  `"토큰 유효기간이 만료되었습니다. 로그인이 필요합니다"` 이러한 문구는 서버에서 응답을 받고 결과 혹은 메시지를 확인한 후 클라이언트에서 설정해주어도 괜찮을 것 같다는 의견을 남겨봅니다🙇‍♀️

2022-02-09 12:28 UTC, CoRoRo10 approved these changes

2022-02-09 14:02 UTC, Kyeong1024 approved these changes

2022-02-09 23:49 UTC, merged